name: Level 4a - Branch specific push

on: 
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Greet
              run: echo "Hello World from dev branch"

