name: Level 4c - Manual Trigger

on: 
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Greet
              run: echo "Hello World from dev branch"

